### PR TITLE
Cleanup Modal Pages

### LINKED ISSUE #23: [App] Remove Custom Renderers for iOS/Android for Contribution Data Entry
There are several custom renderers inside of iOS/Android that make the apps look like Windows applications. We should use standard data entry types on each platform.

### PR DESCRIPTION
**Pull request by jamesmontemagno**
* Update color for navigation and tabs to MVP color
* Wrap all pages in navigation page and add in proper icons on each
* Use Circle Image!
* Update settings page to be nicer
* Add new Android launcher icons
* New Dark Primary (4 shades darker than primary)

Fixes #23 by removing renderers as well on Android

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@sthewissen  what do you think?

**Comment by sthewissen** [comment]
Some minor nitpicks:

- On iOS the status bar/navigation bar colors are all over the place at the moment. It changes back and forth throughout the app (and sometimes gets stuck on a color that isn't correct like a white statusbar on a white navbar. I think that for iOS we need to fix this behavior by settling on one set of colors and applying it to all the screens.

- Our buttons are currently Sign Out and Sign in (capitalization) (very minor nitpick)
- I would probably bump the text size of the about page down a bit on iOS and tweak the font sizes on some other stuff in iOS as well (I can do that in a new PR if needed).

**Comment by sthewissen** [comment]
For the first bullet on my previous comment I'd suggest switching to a blue navbar and white statusbar for the entire app. It would save a lot of hassle while still looking good. Will probably implement that in a future PR once this gets merged.

**Comment by jamesmontemagno** [comment]
Cleaning up now

**Pull request merged**
